import { facts, formatEuro, monthlyFor, offer, priceFor } from "@/config/offer";
import type { Article } from "@/content/types";

export const articles: Article[] = [
  {
    slug: "/blog/quanto-custa-iptv-portugal",
    category: "Preços",
    publishedAt: "2026-09-25T08:00:00Z",
    updated: "2026-09-25",
    keyword: "quanto custa iptv",
    seoTitle: "Quanto Custa IPTV em Portugal em 2026? Preços Reais",
    description: "Quanto custa IPTV em Portugal: preços mensais e anuais, custo por ecrã, custos escondidos (apps, equipamento) e comparação com a TV do operador.",
    eyebrow: "Preços",
    h1: "Quanto custa IPTV em Portugal em 2026?",
    summary: `Os nossos planos começam em ${formatEuro(priceFor(1, 1))} por 1 mês, ${formatEuro(priceFor(1, 3))} por 3 meses, ${formatEuro(priceFor(1, 6))} por 6 meses e ${formatEuro(priceFor(1, 12))} por 12 meses (cerca de ${formatEuro(monthlyFor(1, 12))}/mês) para 1 dispositivo. Podes escolher até 4 dispositivos em simultâneo. A isto podes somar o equipamento e, em algumas apps, uma ativação paga ao programador.`,
    blocks: [
      { t: "h2", text: "Preço por duração" },
      {
        t: "table",
        caption: "Preços para 1 dispositivo",
        head: ["Plano", "Preço total", "Por mês"],
        rows: offer.months.map((m) => [m === 1 ? "1 mês" : `${m} meses`, formatEuro(priceFor(1, m)), formatEuro(monthlyFor(1, m))]),
      },
      { t: "p", text: "Compara o preço total, a duração e o número de dispositivos em simultâneo que precisas." },
      { t: "h2", text: "Preço por número de ecrãs" },
      { t: "p", text: `Se várias pessoas veem ao mesmo tempo, escolhe o número de dispositivos pretendido. Por exemplo, 3 meses para 2 dispositivos custam ${formatEuro(priceFor(2, 3))} e 12 meses para 4 dispositivos custam ${formatEuro(priceFor(4, 12))}. Vê a tabela completa em [preços](/precos).` },
      { t: "h2", text: "Custos que muitas pessoas esquecem" },
      {
        t: "ul",
        items: [
          "**Equipamento**: se a tua Smart TV for antiga, um Fire TV Stick 4K ou uma box Android é um custo único.",
          "**Ativação da app**: apps como IBO Player ou Smart IPTV têm uma ativação paga ao programador depois do período de teste.",
          "**Internet**: precisas de uma ligação estável — 10 Mbps para HD, 25 Mbps para 4K.",
        ],
      },
      { t: "h2", text: "Desconfia dos preços demasiado baixos" },
      { t: "p", text: "Planos «vitalícios» ou anuais a preços irrealistas costumam acabar antes do tempo. Lê [como evitar burlas IPTV](/blog/como-evitar-burlas-iptv) antes de pagar." },
      { t: "cta", kind: "pricing" },
    ],
    faq: [
      { q: "Qual o plano IPTV mais barato por mês?", a: `O plano de 12 meses: cerca de ${formatEuro(monthlyFor(1, 12))} por mês para 1 dispositivo.` },
      { q: "Há custos de ativação?", a: "Não da nossa parte. Algumas apps de Smart TV cobram uma ativação ao programador da app." },
    ],
    related: ["/precos", "/iptv-vs-meo-nos-vodafone", "/blog/como-evitar-burlas-iptv"],
  },
  {
    slug: "/blog/como-evitar-burlas-iptv",
    category: "Segurança",
    publishedAt: "2026-09-25T08:00:00Z",
    updated: "2026-09-25",
    keyword: "burlas iptv",
    seoTitle: "Burlas IPTV: 8 Sinais para Não Perderes Dinheiro",
    description: "Como identificar burlas IPTV em Portugal: 8 sinais de alerta, perguntas a fazer antes de pagar e o que fazer se já pagaste a um fornecedor falso.",
    eyebrow: "Segurança",
    h1: "Burlas IPTV: 8 sinais de alerta antes de pagares",
    summary: "As burlas IPTV mais comuns são planos «vitalícios», preços anuais irrealistas, vendedores que desaparecem depois do pagamento e sites sem contacto real. Antes de pagar, exige um teste grátis, confirma que há apoio que responde em português, compara o preço com o mercado e evita pagamentos sem qualquer rasto.",
    blocks: [
      { t: "h2", text: "8 sinais de alerta" },
      {
        t: "ol",
        items: [
          "**Plano vitalício** — nenhum serviço consegue garantir acesso para sempre.",
          "**Preço anual muito abaixo do mercado** — em Portugal, menos de 2€/mês é um alerta.",
          "**Sem teste grátis** — um fornecedor confiante deixa-te experimentar.",
          "**Pressão para pagar já** — «só hoje», «últimas vagas».",
          "**Sem contacto direto** — só formulário ou redes sociais que não respondem.",
          "**Promessas absolutas** — «zero cortes garantidos», «todos os canais do mundo».",
          "**Apps desconhecidas** enviadas por link sem origem clara.",
          "**Pedido de dados desnecessários**, como códigos de verificação ou palavras-passe de outras contas.",
        ],
      },
      { t: "h2", text: "Perguntas a fazer antes de pagar" },
      {
        t: "ul",
        items: [
          "Posso fazer um teste grátis no meu equipamento?",
          "Quantos dispositivos posso usar ao mesmo tempo?",
          "Como recebo os dados e que app devo usar?",
          "O que acontece se um canal deixar de funcionar?",
        ],
      },
      { t: "h2", text: "Já pagaste a um fornecedor falso?" },
      { t: "p", text: "Guarda as conversas e os comprovativos, contacta o teu banco ou o serviço de pagamento para tentar reverter a transação e, se instalaste uma app suspeita, desinstala-a e muda as palavras-passe usadas nesse equipamento." },
      { t: "callout", tone: "tip", title: "A nossa abordagem", text: `Preços públicos, teste grátis de ${offer.trialHours} horas e apoio ${offer.support} pelo WhatsApp. Compara-nos com os [9 critérios para escolher uma lista IPTV](/melhor-lista-iptv).` },
      { t: "cta", kind: "trial" },
    ],
    related: ["/melhor-lista-iptv", "/teste-iptv-gratis", "/blog/quanto-custa-iptv-portugal"],
  },
  {
    slug: "/blog/internet-minima-para-iptv",
    category: "Rede",
    publishedAt: "2026-09-25T08:00:00Z",
    updated: "2026-09-25",
    keyword: "velocidade internet iptv",
    seoTitle: "Que Internet Preciso para IPTV? Mbps para HD e 4K",
    description: "Velocidade de internet necessária para IPTV: Mbps para SD, HD, Full HD e 4K, por ecrã, e como medir corretamente no teu equipamento.",
    eyebrow: "Rede",
    h1: "Que velocidade de internet preciso para IPTV?",
    summary: "Para IPTV precisas de cerca de 5 Mbps estáveis em SD, 10 Mbps em HD e Full HD e 25 Mbps ou mais em 4K — por cada ecrã a ver ao mesmo tempo. Mais importante do que a velocidade máxima é a estabilidade: uma ligação por cabo com 30 Mbps é melhor do que Wi-Fi fraco com 200 Mbps.",
    blocks: [
      { t: "h2", text: "Velocidade recomendada por qualidade" },
      {
        t: "table",
        head: ["Qualidade", "Velocidade estável por ecrã", "Dados por hora (aprox.)"],
        rows: [
          ["SD", "5 Mbps", "0,7 GB"],
          ["HD / Full HD", "10 Mbps", "1,5 a 3 GB"],
          ["4K", "25 Mbps ou mais", "7 GB ou mais"],
        ],
      },
      { t: "p", text: "Se tiveres 2 ecrãs em 4K ao mesmo tempo, conta com pelo menos 50 Mbps só para o IPTV, mais o que o resto da casa usa." },
      { t: "h2", text: "Como medir corretamente" },
      {
        t: "ol",
        items: [
          "Mede **no próprio equipamento** (TV, box ou Fire TV), não no telemóvel.",
          "Mede à **hora a que costumas ver** televisão, por exemplo às 21h.",
          "Repete o teste por **cabo e por Wi-Fi** para veres a diferença.",
        ],
      },
      { t: "h2", text: "Fibra, cabo, 4G/5G e satélite" },
      { t: "p", text: "Fibra é o ideal. Cabo coaxial funciona bem. Internet móvel 4G/5G funciona se o sinal for bom, mas conta com o consumo de dados. Ligações por satélite com latência alta podem causar mais interrupções." },
      { t: "callout", tone: "tip", title: "Tens cortes?", text: "Vê as [10 soluções para o buffering](/resolver-buffering-iptv)." },
      { t: "cta", kind: "trial" },
    ],
    related: ["/resolver-buffering-iptv", "/iptv-futebol", "/instalar-iptv"],
  },
  {
    slug: "/blog/iptv-varios-dispositivos",
    category: "Guias",
    publishedAt: "2026-09-27T08:00:00Z",
    updated: "2026-09-27",
    keyword: "iptv varios dispositivos",
    seoTitle: "IPTV em Vários Dispositivos: Como Funciona e Quanto Custa",
    description: "Como usar IPTV em várias TVs e telemóveis: diferença entre instalar e ver em simultâneo, que plano escolher e preços de 1 a 4 dispositivos.",
    eyebrow: "Guias",
    h1: "IPTV em vários dispositivos: como funciona",
    summary: `Podes instalar a app IPTV em quantos equipamentos quiseres; o que o plano limita é o número de ecrãs a ver ao mesmo tempo. Podes escolher de 1 a 4 dispositivos para qualquer duração. Por exemplo, 3 meses com 2 dispositivos custam ${formatEuro(priceFor(2, 3))} e 12 meses com 4 custam ${formatEuro(priceFor(4, 12))}.`,
    blocks: [
      { t: "h2", text: "Instalar ≠ ver em simultâneo" },
      { t: "p", text: "Podes ter a app na TV da sala, na do quarto e no telemóvel. Se só uma estiver a ver de cada vez, basta 1 dispositivo. Se duas estiverem ligadas ao mesmo tempo, precisas de 2." },
      { t: "h2", text: "Que plano escolher" },
      {
        t: "table",
        head: ["Situação", "Plano"],
        rows: [
          ["Uma pessoa, uma TV", "1 dispositivo"],
          ["Casal que vê em TVs diferentes", "2 dispositivos"],
          ["Família com crianças", "3 dispositivos"],
          ["Casa grande ou segunda habitação", "4 dispositivos"],
        ],
      },
      { t: "h2", text: "Preços por 12 meses" },
      {
        t: "table",
        head: ["Dispositivos", "12 meses", "Por mês"],
        rows: offer.devices.map((d) => [String(d), formatEuro(priceFor(d, 12)), formatEuro(monthlyFor(d, 12))]),
      },
      { t: "callout", tone: "info", title: "Internet para vários ecrãs", text: "Soma a velocidade por ecrã: 2 ecrãs em HD precisam de cerca de 20 Mbps estáveis. Mais em [internet mínima para IPTV](/blog/internet-minima-para-iptv)." },
      { t: "cta", kind: "pricing" },
    ],
    related: ["/precos", "/blog/internet-minima-para-iptv", "/instalar-iptv"],
  },
  {
    slug: "/blog/epg-catch-up-iptv",
    category: "Guias",
    publishedAt: "2026-09-29T08:00:00Z",
    updated: "2026-09-29",
    keyword: "epg iptv",
    seoTitle: "EPG e Catch-Up no IPTV: O Que São e Como Usar",
    description: "O que é o EPG (guia TV) e o Catch-Up no IPTV, como ativá-los nas apps mais usadas e o que fazer quando o guia TV aparece vazio.",
    eyebrow: "Guias",
    h1: "EPG e Catch-Up no IPTV: o que são e como usar",
    summary: "O EPG (Electronic Program Guide) é o guia TV: mostra o que está a dar e a seguir em cada canal. O Catch-Up permite ver programas que já passaram, nos canais que o suportam. Com login Xtream Codes, as apps carregam o EPG automaticamente; se o guia aparecer vazio, atualiza o EPG na app ou volta a carregar a lista.",
    blocks: [
      { t: "h2", text: "EPG: o guia TV" },
      { t: "p", text: "O EPG aparece como uma grelha com canais e horas. Serve para saber o que está a dar, programar lembretes e, em algumas apps, gravar." },
      { t: "h2", text: "Catch-Up: voltar atrás no tempo" },
      { t: "p", text: "Nos canais com Catch-Up (normalmente marcados com um ícone de relógio), abres o guia, recuas para um programa que já passou e carregas para ver." },
      { t: "h2", text: "Como ativar nas apps" },
      {
        t: "table",
        head: ["App", "EPG", "Catch-Up"],
        rows: [
          ["TiviMate", "Automático com Xtream", "Sim, a partir do guia"],
          ["IPTV Smarters Pro", "Automático com Xtream", "Sim, no menu do canal"],
          ["IBO Player", "Automático", "Depende da versão"],
          ["VLC", "Não tem", "Não"],
        ],
      },
      { t: "h2", text: "O guia TV aparece vazio?" },
      {
        t: "ol",
        items: [
          "Na app, procura «Atualizar EPG» e espera alguns minutos.",
          "Confirma que a data e a hora do equipamento estão certas.",
          "Se usas M3U, pede-nos o link EPG e adiciona-o na app — ou muda para Xtream Codes.",
        ],
      },
      { t: "cta", kind: "trial" },
    ],
    related: ["/lista-m3u-vs-xtream-codes", "/melhores-apps-iptv", "/lista-iptv-portugal"],
  },
  {
    slug: "/blog/iptv-portugueses-no-estrangeiro",
    category: "Guias",
    publishedAt: "2026-10-01T08:00:00Z",
    updated: "2026-10-01",
    keyword: "iptv portugueses no estrangeiro",
    seoTitle: "IPTV para Portugueses no Estrangeiro: Canais de Portugal",
    description: "Como ver canais portugueses fora de Portugal com IPTV: França, Suíça, Luxemburgo, Reino Unido e mais. Equipamentos, internet e dicas.",
    eyebrow: "Emigrantes",
    h1: "IPTV para portugueses no estrangeiro: ver Portugal em qualquer país",
    summary: `Com IPTV, vês os canais portugueses em qualquer país com uma boa ligação à internet — França, Suíça, Luxemburgo, Reino Unido, Alemanha, Canadá ou outro. Instalas uma app na Smart TV, num Fire TV Stick ou no telemóvel e usas a mesma lista, com ${facts.channels} e ${facts.vod}. O teste grátis de ${offer.trialHours} horas funciona também fora de Portugal.`,
    blocks: [
      { t: "h2", text: "Porque o IPTV é a solução mais simples" },
      {
        t: "ul",
        items: [
          "Não precisas de antena parabólica nem de contrato com um operador português.",
          "Funciona com a internet que já tens no país onde vives.",
          "Vês na TV, no tablet e no telemóvel com a mesma subscrição.",
          "Guia TV em hora de Portugal ou local, conforme a app.",
        ],
      },
      { t: "h2", text: "O que precisas" },
      {
        t: "ol",
        items: [
          "Internet estável: 10 Mbps por ecrã em HD.",
          "Um equipamento compatível — vê os [guias de instalação](/instalar-iptv).",
          "Os dados de acesso — começa pelo [teste grátis](/teste-iptv-gratis).",
        ],
      },
      { t: "h2", text: "Fuso horário e guia TV" },
      { t: "p", text: "Em apps como o TiviMate podes ajustar o desvio horário do guia TV para veres a programação na hora local. Útil em países com fuso diferente, como o Brasil ou o Canadá." },
      { t: "callout", tone: "tip", title: "Pagamento a partir do estrangeiro", text: "O pedido e o pagamento são tratados pelo WhatsApp, estejas onde estiveres. Indica o teu país na mensagem." },
      { t: "cta", kind: "trial" },
    ],
    related: ["/lista-iptv-portugal", "/instalar-iptv", "/teste-iptv-gratis"],
  },
];
