import { facts, formatEuro, lowestMonthly, offer, priceFor } from "@/config/offer";
import type { Page } from "@/content/types";

const updated = "2026-09-25";

export const guidePages: Page[] = [
  {
    slug: "/melhor-lista-iptv",
    kind: "guide",
    nav: "Como escolher",
    keyword: "melhor lista iptv",
    seoTitle: "Melhor Lista IPTV em Portugal: 9 Critérios para Escolher",
    description: "Como escolher a melhor lista IPTV em Portugal: 9 critérios objetivos (estabilidade, canais, apoio, preço, teste) e os sinais de alerta a evitar.",
    eyebrow: "Guia de escolha",
    h1: "Como escolher a melhor lista IPTV em Portugal: 9 critérios",
    summary: "A melhor lista IPTV não é a que promete mais canais, mas a que se mantém estável no horário nobre, tem os canais portugueses que vês, guia TV correto, apoio em português que responde, preços claros sem fidelização e um teste grátis para confirmares tudo antes de pagar. Usa os 9 critérios abaixo para comparar qualquer fornecedor — incluindo o nosso.",
    updated,
    blocks: [
      { t: "h2", text: "Os 9 critérios" },
      {
        t: "table",
        caption: "Checklist para comparar fornecedores de IPTV",
        head: ["#", "Critério", "Como verificar"],
        rows: [
          ["1", "Estabilidade no horário nobre", "Testa entre as 20h e as 23h e durante um jogo de futebol"],
          ["2", "Canais que realmente vês", "Procura os teus 10 canais mais vistos no teste, não o número total"],
          ["3", "Qualidade de imagem", "Confirma HD/Full HD nos canais principais e 4K onde anunciado"],
          ["4", "Guia TV (EPG) correto", "O programa indicado corresponde ao que está a dar?"],
          ["5", "Rapidez a mudar de canal", "Deve demorar poucos segundos, sem ecrã preto prolongado"],
          ["6", "Apoio em português", "Envia uma pergunta e mede o tempo e a qualidade da resposta"],
          ["7", "Preço claro", "Preço total visível, por duração e por número de ecrãs"],
          ["8", "Sem fidelização", "Pagas um período e decides se renovas"],
          ["9", "Teste grátis", "Um fornecedor confiante deixa-te testar antes de pagar"],
        ],
      },
      { t: "h2", text: "Sinais de alerta" },
      {
        t: "ul",
        items: [
          "**Planos vitalícios** ou preços anuais muito abaixo do mercado — normalmente o serviço desaparece antes do fim.",
          "**Sem teste** e pagamento imediato por métodos sem qualquer proteção.",
          "**Promessas absolutas** como «zero cortes garantidos» — nenhuma transmissão pela internet é perfeita.",
          "**Sem contacto real**: só formulário, sem resposta em horas.",
        ],
      },
      {
        t: "p",
        text: "Aprofundamos este tema em [como evitar burlas IPTV](/blog/como-evitar-burlas-iptv).",
      },
      { t: "h2", text: "Como nos avaliamos a nós próprios" },
      {
        t: "p",
        text: `Publicamos os nossos factos para que possas comparar: ${facts.channels}, ${facts.vod}, qualidade até 4K, guia TV e Catch-Up, apoio ${offer.support}, planos de 1 a 12 meses sem fidelização (cerca de ${formatEuro(lowestMonthly)}/mês no plano anual) e teste grátis de ${offer.trialHours} horas. Não te pedimos que acredites — pedimos que testes.`,
      },
      { t: "facts" },
      { t: "h2", text: "Número de canais: importa mesmo?" },
      {
        t: "p",
        text: "Até certo ponto. Uma lista grande dá-te canais de muitos países e mais escolha em desporto e cinema, mas o que decide a experiência é a estabilidade dos canais que vês todos os dias. Por isso o teste deve focar-se nos teus canais, não no total.",
      },
      { t: "cta", kind: "trial" },
    ],
    faq: [
      { q: "Qual é a melhor lista IPTV em Portugal?", a: "É a que passa nos 9 critérios deste guia no teu equipamento e com a tua internet. Por isso recomendamos sempre um teste grátis antes de pagar." },
      { q: "Listas IPTV grátis valem a pena?", a: "Raramente. Listas grátis costumam ser instáveis, desaparecer sem aviso e podem expor-te a riscos de segurança. Para uso diário, um serviço com apoio é mais fiável." },
      { q: "Quanto deve custar uma boa lista IPTV?", a: `Compara a duração e o número de dispositivos em simultâneo. Os nossos preços começam em ${formatEuro(priceFor(1, 1))} por 1 mês com 1 dispositivo.` },
    ],
    related: ["/teste-iptv-gratis", "/blog/como-evitar-burlas-iptv", "/precos", "/iptv-vs-meo-nos-vodafone"],
  },
  {
    slug: "/melhores-apps-iptv",
    kind: "guide",
    nav: "Melhores apps",
    keyword: "melhores apps iptv",
    seoTitle: "Melhores Apps IPTV 2026: TiviMate, Smarters, IBO e Mais",
    description: "Comparativo das melhores apps IPTV em 2026 para Smart TV, Fire TV, Android, iPhone e PC: TiviMate, IPTV Smarters, IBO Player, GSE, VLC e mais.",
    eyebrow: "Comparativo",
    h1: "Melhores apps IPTV em 2026: qual escolher para cada equipamento",
    summary: "Para Fire TV e Android TV, a melhor app IPTV é o TiviMate (canais e guia TV) ou o IPTV Smarters Pro (mais simples, com filmes e séries). Em Smart TV Samsung e LG, IBO Player e Smart IPTV são as mais usadas. No iPhone e iPad, Smarters Player Lite, GSE Smart IPTV ou IPTVX. No computador, VLC para testar e IPTV Smarters para uso diário. Todas funcionam com a nossa lista.",
    updated,
    blocks: [
      { t: "h2", text: "Tabela comparativa" },
      {
        t: "table",
        head: ["App", "Equipamentos", "Preço", "Melhor para"],
        rows: [
          ["TiviMate", "Android TV, Google TV, Fire TV", "Grátis + Premium pago", "Canais em direto e guia TV"],
          ["IPTV Smarters Pro", "Android, Fire TV, Windows, Mac", "Grátis", "Tudo numa app simples"],
          ["IBO Player", "Samsung, LG, Android, Fire TV", "Teste + ativação paga", "Smart TV"],
          ["Smart IPTV (SIPTV)", "Samsung, LG, Android TV", "Teste + ativação paga", "Smart TV antigas"],
          ["OTT Navigator", "Android, Fire TV", "Grátis + Premium", "Utilizadores avançados"],
          ["GSE Smart IPTV", "iPhone, iPad, Apple TV, Android", "Grátis + compras", "Apple com muitas opções"],
          ["IPTVX", "iPhone, iPad, Apple TV, Mac", "Paga", "Interface premium em Apple"],
          ["VLC", "Windows, Mac, Linux, móvel", "Grátis", "Testes rápidos com M3U"],
        ],
      },
      { t: "h2", text: "TiviMate — o melhor para Android TV e Fire TV" },
      {
        t: "p",
        text: "Interface ao estilo de uma box de operador, com guia TV em grelha, favoritos, gravação e Catch-Up. A versão gratuita é limitada; a Premium (paga ao programador) desbloqueia várias listas, gravação e personalização. Ideal se vês sobretudo canais em direto. Guia: [Fire TV Stick](/instalar-iptv/fire-tv-stick).",
      },
      { t: "h2", text: "IPTV Smarters Pro — a mais simples" },
      {
        t: "p",
        text: "Junta canais, filmes e séries em menus claros e aceita Xtream Codes e M3U. É uma boa primeira app para quem nunca usou IPTV. No iPhone e iPad existe como **Smarters Player Lite**.",
      },
      { t: "h2", text: "IBO Player e Smart IPTV — para Smart TV" },
      {
        t: "p",
        text: "Funcionam com o endereço MAC da TV: a lista fica associada ao aparelho. Têm um período de teste e depois uma ativação paga diretamente ao programador. Vê os guias para [Samsung](/instalar-iptv/smart-tv-samsung) e [LG](/instalar-iptv/smart-tv-lg).",
      },
      { t: "h2", text: "Como escolher" },
      {
        t: "ul",
        items: [
          "Vês sobretudo **canais em direto e desporto**? TiviMate.",
          "Queres **filmes e séries** fáceis de encontrar? IPTV Smarters Pro.",
          "Não queres comprar nada e tens **Smart TV**? IBO Player ou Smart IPTV.",
          "Usas **Apple**? GSE Smart IPTV ou IPTVX.",
        ],
      },
      {
        t: "callout",
        tone: "warn",
        title: "A app não inclui canais",
        text: "Nenhuma destas apps vende ou inclui conteúdo: são leitores. Desconfia de apps que prometem canais grátis incluídos.",
      },
      { t: "cta", kind: "trial" },
    ],
    faq: [
      { q: "Qual é a melhor app IPTV grátis?", a: "IPTV Smarters Pro em Android e Fire TV, e VLC no computador. A versão gratuita do TiviMate também serve para começar." },
      { q: "Preciso de pagar a app e a lista?", a: "A lista (subscrição) é paga ao fornecedor. A app pode ser gratuita ou ter uma versão/ativação paga ao programador da app — são coisas diferentes." },
      { q: "Posso usar várias apps com a mesma lista?", a: "Sim, desde que não excedas o número de dispositivos em simultâneo do teu plano." },
    ],
    related: ["/instalar-iptv", "/lista-m3u-vs-xtream-codes", "/instalar-iptv/fire-tv-stick", "/teste-iptv-gratis"],
  },
  {
    slug: "/lista-m3u-vs-xtream-codes",
    kind: "guide",
    nav: "M3U vs Xtream",
    keyword: "lista m3u",
    seoTitle: "Lista M3U vs Xtream Codes: Diferenças e Qual Usar",
    description: "O que é uma lista M3U, o que é Xtream Codes e qual escolher na tua app IPTV. Explicação simples, exemplos e resolução de erros comuns.",
    eyebrow: "Explicação",
    h1: "Lista M3U vs Xtream Codes: qual usar na tua app IPTV",
    summary: "Uma lista M3U é um link (ou ficheiro) com todos os canais; o Xtream Codes é um login com servidor, utilizador e palavra-passe. Os dois dão acesso ao mesmo conteúdo, mas o Xtream Codes é mais prático: carrega automaticamente o guia TV, separa canais, filmes e séries e atualiza a lista sozinho. Sempre que a tua app aceitar, usa Xtream Codes.",
    updated,
    blocks: [
      { t: "h2", text: "Diferenças principais" },
      {
        t: "table",
        head: ["", "M3U", "Xtream Codes"],
        rows: [
          ["Formato", "Um link longo (URL) ou ficheiro .m3u", "Servidor + utilizador + palavra-passe"],
          ["Guia TV (EPG)", "Muitas vezes exige um link EPG separado", "Carrega automaticamente"],
          ["Filmes e séries", "Misturados com os canais", "Separados em menus próprios"],
          ["Atualizações", "Depende da app", "Automáticas"],
          ["Compatibilidade", "Quase todas as apps e o VLC", "A maioria das apps modernas"],
        ],
      },
      { t: "h2", text: "Como é um link M3U" },
      {
        t: "p",
        text: "Um link M3U contém normalmente o endereço do servidor e os teus dados, por isso **nunca o partilhes** — quem tiver o link usa a tua subscrição.",
      },
      { t: "h2", text: "Quando usar cada um" },
      {
        t: "ul",
        items: [
          "**Xtream Codes**: TiviMate, IPTV Smarters, IBO Player, GSE Smart IPTV — sempre que houver essa opção.",
          "**M3U**: VLC, Smart IPTV (SIPTV), Kodi com PVR IPTV Simple Client e apps que só aceitam link.",
        ],
      },
      { t: "h2", text: "Erros comuns" },
      {
        t: "table",
        head: ["Erro", "Causa provável", "Solução"],
        rows: [
          ["«Login falhou»", "Dados mal escritos", "Copia e cola os dados; atenção a maiúsculas e espaços"],
          ["Lista vazia", "Link M3U incompleto", "Confirma que copiaste o link inteiro"],
          ["Sem guia TV", "M3U sem EPG", "Usa Xtream Codes ou pede o link EPG"],
          ["«Conta expirada»", "Fim do teste ou do plano", "Renova em [preços](/precos)"],
        ],
      },
      { t: "cta", kind: "trial" },
    ],
    faq: [
      { q: "O que é uma lista M3U?", a: "É um formato de lista de reprodução: um link ou ficheiro com os endereços dos canais, que as apps IPTV e o VLC conseguem abrir." },
      { q: "O que é Xtream Codes?", a: "É um método de login para IPTV com servidor, utilizador e palavra-passe. A app vai buscar sozinha canais, filmes, séries e guia TV." },
      { q: "Recebo M3U ou Xtream Codes?", a: "Podes receber os dois. Indica-nos a tua app e enviamos o formato certo." },
    ],
    related: ["/melhores-apps-iptv", "/instalar-iptv", "/instalar-iptv/pc-windows-mac", "/lista-iptv-portugal"],
  },
  {
    slug: "/iptv-vs-meo-nos-vodafone",
    kind: "guide",
    nav: "IPTV vs operadores",
    keyword: "iptv vs meo",
    seoTitle: "IPTV vs MEO, NOS e Vodafone: Diferenças e Custos",
    description: "Comparação honesta entre IPTV e a TV dos operadores (MEO, NOS, Vodafone, DIGI): preço, fidelização, canais, equipamentos e para quem é cada opção.",
    eyebrow: "Comparação",
    h1: "IPTV ou TV do operador (MEO, NOS, Vodafone): o que compensa?",
    summary: `A TV dos operadores vem normalmente num pacote com internet e telefone, com box própria e fidelização que pode chegar a 24 meses. Um serviço IPTV usa a internet que já tens, funciona em vários equipamentos, não tem fidelização e custa ${facts.fromMonthly} no plano anual, com ${facts.channels} de vários países. O operador dá a experiência mais integrada; o IPTV dá mais canais internacionais e mais flexibilidade.`,
    updated,
    blocks: [
      { t: "h2", text: "Comparação lado a lado" },
      {
        t: "table",
        head: ["", "Operador (MEO, NOS, Vodafone, DIGI)", "IPTV"],
        rows: [
          ["Como funciona", "Box do operador ligada à sua rede", "App no teu equipamento, através de qualquer internet"],
          ["Fidelização", "Comum em pacotes, até 24 meses", "Sem fidelização"],
          ["Canais internacionais", "Poucos, muitas vezes pagos à parte", "Dezenas de países incluídos"],
          ["Equipamentos", "Box do operador e app própria", "Smart TV, Fire TV, box Android, telemóvel, PC"],
          ["Fora de casa / estrangeiro", "Limitado", "Funciona em qualquer rede com internet"],
          ["Instalação", "Técnico ou kit do operador", "App instalada em minutos"],
        ],
      },
      { t: "h2", text: "Quando o operador faz mais sentido" },
      {
        t: "ul",
        items: [
          "Queres **um único contrato** para internet, telemóvel e TV.",
          "Preferes uma **box única com comando** e sem configurar nada.",
          "Valorizas funcionalidades específicas do operador, como gravações na box.",
        ],
      },
      { t: "h2", text: "Quando o IPTV faz mais sentido" },
      {
        t: "ul",
        items: [
          "Já tens internet e **não queres fidelização** de TV.",
          "Queres **canais de outros países** (família no estrangeiro, emigrantes, estrangeiros a viver em Portugal).",
          "Queres ver no **telemóvel, tablet ou numa segunda casa** com a mesma subscrição.",
        ],
      },
      {
        t: "callout",
        tone: "tip",
        title: "Posso manter só a internet do operador?",
        text: "Muitas pessoas mantêm um pacote só de internet e usam IPTV para a televisão. Antes de mudar, confirma as condições do teu contrato atual, sobretudo se ainda estiveres dentro do período de fidelização.",
      },
      { t: "h2", text: "E a qualidade?" },
      {
        t: "p",
        text: "A qualidade do IPTV depende muito da tua ligação e do equipamento. Com fibra e cabo de rede, a experiência é muito próxima da de uma box de operador. Vê [a internet mínima para IPTV](/blog/internet-minima-para-iptv).",
      },
      { t: "cta", kind: "pricing" },
    ],
    faq: [
      { q: "O IPTV substitui a box da MEO ou da NOS?", a: "Para ver televisão, sim: instalas uma app na Smart TV ou num Fire TV Stick. Continuas a precisar de uma ligação à internet." },
      { q: "Preciso de fibra para IPTV?", a: "Não é obrigatório, mas ajuda. Para HD bastam cerca de 10 Mbps estáveis; para 4K, 25 Mbps ou mais." },
    ],
    related: ["/precos", "/blog/quanto-custa-iptv-portugal", "/melhor-lista-iptv", "/blog/internet-minima-para-iptv"],
  },
  {
    slug: "/iptv-futebol",
    kind: "guide",
    nav: "IPTV futebol",
    keyword: "iptv futebol",
    seoTitle: "IPTV para Futebol e Desporto em Portugal: Guia 2026",
    description: "Como ver futebol e desporto com IPTV em Portugal: canais desportivos, eventos PPV, qualidade 4K, atraso da transmissão e dicas para jogos sem cortes.",
    eyebrow: "Desporto",
    h1: "IPTV para futebol e desporto: como ver os jogos sem cortes",
    summary: "A lista inclui canais de desporto portugueses e internacionais e eventos PPV: futebol português e europeu, Fórmula 1, NBA, ténis e desportos de combate. Para ver jogos sem cortes, usa cabo de rede, pelo menos 10 Mbps estáveis (25 Mbps para 4K), uma app com bom leitor como o TiviMate e confirma os teus canais no teste grátis antes de um jogo importante.",
    updated,
    blocks: [
      { t: "h2", text: "Que desporto podes ver" },
      {
        t: "ul",
        items: [
          "**Futebol**: campeonato português, taças, competições europeias e as principais ligas estrangeiras.",
          "**Motores**: Fórmula 1, MotoGP e outras competições.",
          "**Basquetebol**: NBA e ligas europeias.",
          "**Ténis, ciclismo, combate e mais**, incluindo eventos PPV.",
        ],
      },
      {
        t: "callout",
        tone: "tip",
        title: "Tens um jogo importante esta semana?",
        text: `Pede o [teste grátis de ${offer.trialHours} horas](/teste-iptv-gratis) um ou dois dias antes e confirma o canal e a qualidade — não no próprio dia do jogo.`,
      },
      { t: "h2", text: "Checklist para jogos sem cortes" },
      {
        t: "ol",
        items: [
          "Liga a TV ou a box ao router **por cabo**.",
          "Fecha downloads e atualizações noutros aparelhos durante o jogo.",
          "Usa uma app com bom leitor (TiviMate ou IPTV Smarters) e o equipamento mais rápido da casa.",
          "Se houver cortes, experimenta a versão HD do canal em vez da 4K.",
          "Reinicia o router e o equipamento antes de um jogo grande.",
        ],
      },
      { t: "h2", text: "Porque é que o IPTV tem algum atraso?" },
      {
        t: "p",
        text: "Todas as transmissões pela internet têm um pequeno atraso em relação ao sinal original, porque o vídeo é codificado e enviado em blocos. É normal ouvires um vizinho festejar um golo alguns segundos antes. Não afeta a qualidade.",
      },
      { t: "h2", text: "Qualidade 4K no desporto" },
      {
        t: "p",
        text: "Os eventos em 4K exigem mais da tua internet e do equipamento. Com um Fire TV Stick 4K ou uma box Android 4K e ligação estável de 25 Mbps ou mais, a diferença de nitidez nota-se sobretudo em ecrãs grandes.",
      },
      { t: "cta", kind: "trial" },
    ],
    faq: [
      { q: "A lista tem os canais de desporto portugueses?", a: "Sim, a secção de Portugal inclui canais de desporto. Como as grelhas mudam, confirma os canais que precisas no teste grátis." },
      { q: "Porque é que o jogo para no momento mais importante?", a: "Na maioria dos casos é a rede de casa: Wi-Fi fraco ou vários aparelhos a usar a internet. Vê o guia para resolver o buffering." },
    ],
    related: ["/resolver-buffering-iptv", "/lista-iptv-portugal", "/teste-iptv-gratis", "/blog/internet-minima-para-iptv"],
  },
  {
    slug: "/resolver-buffering-iptv",
    kind: "guide",
    nav: "Resolver buffering",
    keyword: "iptv buffering",
    seoTitle: "IPTV a Parar ou com Buffering? 10 Soluções que Funcionam",
    description: "O IPTV está sempre a parar? 10 soluções testadas para acabar com o buffering: rede, Wi-Fi, DNS, app, equipamento e quando falar com o apoio.",
    eyebrow: "Resolução de problemas",
    h1: "IPTV a parar ou com buffering: 10 soluções que funcionam",
    summary: "O buffering no IPTV tem quase sempre uma de quatro causas: Wi-Fi fraco, internet partilhada por muitos aparelhos, equipamento lento ou definições da app. Começa por ligar o equipamento por cabo, reiniciar o router, fechar outros downloads e mudar o leitor (decoder) nas definições da app. Se o problema for só num canal, fala com o apoio.",
    updated,
    blocks: [
      { t: "h2", text: "Diagnóstico rápido" },
      {
        t: "table",
        head: ["Sintoma", "Causa provável"],
        rows: [
          ["Para em todos os canais", "Rede de casa ou equipamento"],
          ["Para só num canal", "Esse canal específico — avisa o apoio"],
          ["Para só à noite", "Internet congestionada em casa ou no operador"],
          ["Imagem com cortes de som", "Leitor/decoder da app"],
        ],
      },
      { t: "h2", text: "As 10 soluções" },
      {
        t: "steps",
        items: [
          { title: "Liga por cabo de rede", text: "É a solução mais eficaz. Se não for possível, usa adaptadores PLC ou um sistema Wi-Fi mesh." },
          { title: "Reinicia router e equipamento", text: "Desliga ambos da tomada durante 30 segundos." },
          { title: "Mede a velocidade no próprio equipamento", text: "Usa uma app de teste de velocidade na TV ou na box, não no telemóvel. Vê [a internet mínima para IPTV](/blog/internet-minima-para-iptv)." },
          { title: "Usa a banda de 5 GHz", text: "No Wi-Fi, a rede de 5 GHz é mais rápida e tem menos interferências (a 2,4 GHz chega mais longe, mas é mais lenta)." },
          { title: "Fecha outros consumos", text: "Downloads, atualizações de consolas e backups na nuvem competem com o IPTV." },
          { title: "Muda o leitor da app", text: "Nas definições da app, alterna entre leitor nativo/hardware e software (ou o leitor alternativo da app)." },
          { title: "Limpa a cache", text: "Em Android e Fire TV: Definições → Apps → a tua app → Limpar cache." },
          { title: "Muda o DNS", text: "Configura DNS públicos (por exemplo 1.1.1.1 ou 8.8.8.8) no router ou no equipamento." },
          { title: "Baixa a qualidade", text: "Se a internet for limitada, usa a versão HD do canal em vez de 4K." },
          { title: "Fala com o apoio", text: `Se nada resultar, envia-nos o canal, a hora e o equipamento pelo WhatsApp — apoio ${offer.support}.` },
        ],
      },
      {
        t: "callout",
        tone: "info",
        title: "E a VPN?",
        text: "Em algumas redes, uma VPN pode melhorar a estabilidade se o operador limitar o tráfego de vídeo. Noutras, torna tudo mais lento. Experimenta com e sem VPN antes de decidir.",
      },
      { t: "cta", kind: "trial" },
    ],
    faq: [
      { q: "Porque é que o IPTV para mais à noite?", a: "Porque é quando mais pessoas usam a internet, em casa e no operador. Ligar por cabo e fechar outros consumos ajuda muito." },
      { q: "Um equipamento melhor resolve o buffering?", a: "Muitas vezes, sim. Smart TV antigas e boxes baratas têm pouco processador e memória. Um Fire TV Stick 4K costuma ser uma melhoria notória." },
    ],
    related: ["/blog/internet-minima-para-iptv", "/instalar-iptv/fire-tv-stick", "/iptv-futebol", "/melhores-apps-iptv"],
  },
];
