import { facts, formatEuro, lowestMonthly, lowestPrice, offer } from "@/config/offer";
import { siteConfig } from "@/config/site";
import type { Faq, Page } from "@/content/types";

const updated = "2026-09-25";

/** Perguntas gerais — usadas na página de FAQ e (as primeiras) na homepage. */
export const generalFaq: Faq[] = [
  { q: "O que é IPTV?", a: "IPTV (Internet Protocol Television) é televisão transmitida pela internet em vez de antena, cabo ou satélite. Vês os canais através de uma app na Smart TV, num Fire TV Stick, numa box Android, no telemóvel ou no computador." },
  { q: "Quantos canais tem a lista?", a: `${facts.channels} em direto de Portugal e de dezenas de países, mais ${facts.vod} a pedido, em qualidade até 4K.` },
  { q: "Quanto custa?", a: `Desde ${formatEuro(lowestPrice)} por 1 mês com 1 dispositivo, ou cerca de ${formatEuro(lowestMonthly)} por mês no plano de 12 meses com 4 dispositivos incluídos.` },
  { q: "Posso testar antes de pagar?", a: `Sim. O teste grátis de ${offer.trialHours} horas é pedido pelo WhatsApp e não exige cartão nem pagamento.` },
  { q: "Há fidelização?", a: "Não. Pagas o período que escolhes (1, 3, 6 ou 12 meses) e decides no fim se renovas." },
  { q: "Em que equipamentos funciona?", a: "Smart TV Samsung e LG, Android TV e Google TV, Fire TV Stick, box Android, iPhone, iPad, Apple TV, telemóveis Android e computadores Windows e Mac." },
  { q: "Que velocidade de internet preciso?", a: "Cerca de 10 Mbps estáveis para HD e 25 Mbps ou mais para 4K, por cada ecrã em simultâneo. O cabo de rede é mais estável do que Wi-Fi." },
  { q: "Como pago?", a: "Escolhes o plano no site, o WhatsApp abre com o pedido e a equipa de apoio envia-te o link de pagamento. Depois recebes os dados de acesso." },
  { q: "Como recebo a lista?", a: "Pelo WhatsApp, em formato Xtream Codes (servidor, utilizador, palavra-passe) e/ou link M3U, com indicação da app mais adequada ao teu equipamento." },
  { q: "Funciona fora de Portugal?", a: "Sim. O serviço funciona em qualquer país com uma boa ligação à internet — útil para quem vive ou viaja no estrangeiro." },
  { q: "Posso usar em vários dispositivos?", a: "Podes instalar em quantos quiseres; o plano define quantos podem ver ao mesmo tempo (de 1 a 4)." },
  { q: "Tem guia TV e Catch-Up?", a: "Sim. As apps mostram o guia TV (EPG) e, nos canais com Catch-Up, podes ver programas que já passaram." },
];

export const trustPages: Page[] = [
  {
    slug: "/perguntas-frequentes",
    kind: "trust",
    nav: "Perguntas frequentes",
    keyword: "iptv perguntas frequentes",
    seoTitle: "Perguntas Frequentes sobre IPTV em Portugal | Respostas",
    description: "Respostas diretas sobre IPTV em Portugal: preço, canais, teste grátis, equipamentos, internet necessária, pagamento, fidelização e apoio.",
    eyebrow: "FAQ",
    h1: "Perguntas frequentes sobre IPTV",
    summary: `Respostas curtas às dúvidas mais comuns: o serviço tem ${facts.channels} e ${facts.vod}, planos de 1 a 12 meses para 1 a 4 dispositivos sem fidelização, teste grátis de ${offer.trialHours} horas pelo WhatsApp e apoio ${offer.support}.`,
    updated,
    blocks: [{ t: "cta", kind: "trial" }],
    faq: generalFaq,
    related: ["/precos", "/teste-iptv-gratis", "/instalar-iptv", "/contacto"],
  },
  {
    slug: "/sobre-nos",
    kind: "trust",
    nav: "Sobre nós",
    keyword: "melhor iptv listas",
    seoTitle: "Sobre Nós | Melhor IPTV Listas",
    description: "Quem somos, como trabalhamos e o que prometemos: serviço IPTV com apoio em português, preços públicos, sem fidelização e teste grátis antes de pagar.",
    eyebrow: "Sobre nós",
    h1: "Sobre a Melhor IPTV Listas",
    summary: `A ${siteConfig.name} é um serviço de IPTV para Portugal e para portugueses no estrangeiro, com apoio em português pelo WhatsApp. Publicamos preços e condições no site, não temos fidelização e oferecemos um teste grátis de ${offer.trialHours} horas para que decidas com base no que vês, não no que prometemos.`,
    updated,
    blocks: [
      { t: "h2", text: "Como trabalhamos" },
      {
        t: "ul",
        items: [
          "**Preços públicos**: o preço que vês na [tabela](/precos) é o que pagas — sem taxas escondidas.",
          "**Teste primeiro**: podes experimentar tudo durante 24 horas antes de pagar.",
          "**Sem fidelização**: pagas um período e decides se renovas.",
          `**Apoio humano**: respondemos pelo WhatsApp, ${offer.support}, e ajudamos na instalação.`,
          "**Guias abertos**: publicamos [guias de instalação](/instalar-iptv) e de [resolução de problemas](/resolver-buffering-iptv) gratuitos.",
        ],
      },
      { t: "h2", text: "O que prometemos — e o que não prometemos" },
      {
        t: "p",
        text: "Prometemos transparência, apoio e um serviço que podes testar. Não prometemos «zero cortes»: nenhuma transmissão pela internet é perfeita e a experiência depende também da tua rede e do teu equipamento. Por isso ajudamos-te a configurar tudo da melhor forma.",
      },
      { t: "facts" },
      { t: "cta", kind: "trial" },
    ],
    related: ["/contacto", "/melhor-lista-iptv", "/termos-e-condicoes", "/perguntas-frequentes"],
  },
  {
    slug: "/contacto",
    kind: "trust",
    nav: "Contacto",
    keyword: "contacto iptv",
    seoTitle: "Contacto e Apoio 24/7 pelo WhatsApp | Melhor IPTV Listas",
    description: `Fala connosco pelo WhatsApp ${offer.whatsappDisplay}: teste grátis, planos, pagamento e ajuda na instalação. Apoio ${offer.support}.`,
    eyebrow: "Contacto",
    h1: "Contacto e apoio",
    summary: `O contacto é feito pelo WhatsApp, através do número ${offer.whatsappDisplay}, com apoio ${offer.support}. Usa-o para pedir o teste grátis, escolher um plano, receber o link de pagamento ou pedir ajuda para instalar a app.`,
    updated,
    blocks: [
      { t: "h2", text: "Para que podes contactar-nos" },
      {
        t: "ul",
        items: [
          `Pedir o [teste grátis de ${offer.trialHours} horas](/teste-iptv-gratis).`,
          "Escolher um plano e receber o link de pagamento.",
          "Ajuda para instalar a app no teu equipamento.",
          "Problemas com um canal, com o guia TV ou com a imagem.",
          "Renovar ou alterar o número de dispositivos.",
        ],
      },
      {
        t: "callout",
        tone: "tip",
        title: "Para uma resposta mais rápida",
        text: "Indica logo o teu equipamento (por exemplo «Samsung 2021» ou «Fire TV Stick 4K»), a app que usas e, se for um problema, o canal e a hora em que aconteceu.",
      },
      { t: "cta", kind: "trial" },
    ],
    related: ["/perguntas-frequentes", "/teste-iptv-gratis", "/precos", "/sobre-nos"],
  },
  {
    slug: "/termos-e-condicoes",
    kind: "legal",
    nav: "Termos e condições",
    keyword: "termos e condições",
    seoTitle: "Termos e Condições | Melhor IPTV Listas",
    description: "Termos e condições de utilização do site e do serviço Melhor IPTV Listas: planos, pagamento, teste grátis, utilização e limitações.",
    eyebrow: "Legal",
    h1: "Termos e condições",
    summary: "Estes termos regulam a utilização do site e do serviço. Ao pedir um teste ou subscrever um plano, aceitas as condições abaixo.",
    updated,
    blocks: [
      { t: "h2", text: "1. Serviço" },
      { t: "p", text: "O serviço dá acesso, através da internet, a canais em direto e conteúdos a pedido, para visualização em apps de terceiros instaladas pelo cliente. A qualidade depende também da ligação à internet e do equipamento do cliente." },
      { t: "h2", text: "2. Planos e pagamento" },
      { t: "p", text: "Os planos têm a duração e o número de dispositivos em simultâneo indicados na página de [preços](/precos). O pagamento é feito através do link enviado pela equipa de apoio. Não há renovação automática nem fidelização." },
      { t: "h2", text: "3. Teste grátis" },
      { t: "p", text: `É disponibilizado um teste de ${offer.trialHours} horas por pessoa e por equipamento, para que o cliente confirme a compatibilidade e a qualidade antes de pagar.` },
      { t: "h2", text: "4. Utilização" },
      { t: "p", text: "A subscrição é pessoal. Não é permitido partilhar ou revender os dados de acesso nem exceder o número de dispositivos em simultâneo do plano. O incumprimento pode levar à suspensão do acesso." },
      { t: "h2", text: "5. Apps de terceiros" },
      { t: "p", text: "As apps usadas para ver o serviço (por exemplo TiviMate, IPTV Smarters ou IBO Player) são de terceiros. Eventuais custos de ativação dessas apps são pagos aos respetivos programadores e não fazem parte da subscrição." },
      { t: "h2", text: "6. Responsabilidade do cliente" },
      { t: "p", text: "O cliente é responsável por utilizar o serviço de acordo com a legislação aplicável no país onde se encontra." },
      { t: "h2", text: "7. Alterações" },
      { t: "p", text: "Estes termos podem ser atualizados. A data da última revisão é indicada no topo da página." },
      { t: "h2", text: "8. Contacto" },
      { t: "p", text: "Para qualquer questão sobre estes termos, usa a página de [contacto](/contacto)." },
    ],
    related: ["/politica-de-privacidade", "/contacto"],
  },
  {
    slug: "/politica-de-privacidade",
    kind: "legal",
    nav: "Política de privacidade",
    keyword: "política de privacidade",
    seoTitle: "Política de Privacidade | Melhor IPTV Listas",
    description: "Como tratamos os teus dados: contacto pelo WhatsApp, estatísticas anónimas sem cookies, conservação e os teus direitos ao abrigo do RGPD.",
    eyebrow: "Legal",
    h1: "Política de privacidade",
    summary: "Recolhemos apenas os dados necessários para responder aos teus pedidos e prestar o serviço. O site não usa cookies de publicidade nem de rastreamento e mede visitas de forma anónima.",
    updated,
    blocks: [
      { t: "h2", text: "1. Dados que tratamos" },
      { t: "ul", items: [
        "**Contacto pelo WhatsApp**: o teu número e as mensagens que nos envias, para responder e prestar o serviço.",
        "**Dados do serviço**: plano, datas de início e fim e equipamento indicado, para gerir a tua subscrição.",
        "**Estatísticas do site**: medição anónima e agregada de visitas (Vercel Web Analytics), sem cookies e sem identificar pessoas.",
      ] },
      { t: "h2", text: "2. Cookies" },
      { t: "p", text: "Este site não instala cookies de publicidade, de redes sociais nem de rastreamento. Por isso não mostramos um aviso de cookies." },
      { t: "h2", text: "3. Finalidades" },
      { t: "p", text: "Usamos os dados apenas para responder a pedidos, prestar o serviço, dar apoio e cumprir obrigações legais. Não vendemos nem cedemos dados a terceiros para marketing." },
      { t: "h2", text: "4. Conservação" },
      { t: "p", text: "Conservamos os dados durante a relação com o cliente e pelo tempo necessário para cumprir obrigações legais, sendo depois eliminados." },
      { t: "h2", text: "5. Os teus direitos (RGPD)" },
      { t: "p", text: "Podes pedir acesso, retificação, apagamento, limitação ou portabilidade dos teus dados e opor-te ao seu tratamento, através da página de [contacto](/contacto). Podes também apresentar reclamação à CNPD (Comissão Nacional de Proteção de Dados)." },
      { t: "h2", text: "6. Serviços de terceiros" },
      { t: "p", text: "O WhatsApp é um serviço da Meta, com política de privacidade própria. O site está alojado na Vercel." },
    ],
    related: ["/termos-e-condicoes", "/contacto"],
  },
];
